# Generated by Django 5.0.1 on 2025-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="keycloak_id",
            field=models.UUIDField(
                blank=True, help_text="ID utente in Keycloak", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="keycloak_roles",
            field=models.JSONField(
                blank=True, default=list, help_text="Ruoli dell'utente in Keycloak"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="keycloak_username",
            field=models.CharField(
                blank=True, help_text="Username in Keycloak", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_keycloak_sync",
            field=models.DateTimeField(
                blank=True, help_text="Ultima sincronizzazione con Keycloak", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["keycloak_id"], name="users_keycloa_655743_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
