# Generated by Django 5.0.1 on 2025-09-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "experiments",
            },
        ),
        migrations.CreateModel(
            name="ProcessedDataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "experiment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "processed_datasets",
            },
        ),
        migrations.CreateModel(
            name="ProcessingChain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("processing_method", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "processing_chains",
            },
        ),
        migrations.CreateModel(
            name="RawDataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField()),
                ("upload_user", models.CharField(max_length=150)),
                ("type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                (
                    "processing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.processingchain",
                    ),
                ),
            ],
            options={
                "db_table": "raw_datasets",
            },
        ),
        migrations.CreateModel(
            name="RawProcessedLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "processed_dataset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.processeddataset",
                    ),
                ),
                (
                    "raw_dataset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rawdataset",
                    ),
                ),
            ],
            options={
                "db_table": "raw_processed_links",
            },
        ),
    ]
