# Generated by Django 5.0.1 on 2025-09-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_load_processing_chain_fixtures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdataset",
            name="processing_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.processingchain",
            ),
        ),
        migrations.AlterField(
            model_name="rawdataset",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_processed", "not_processed"),
                    ("processing", "processing"),
                    ("processed", "processed"),
                    ("failed", "failed"),
                ],
                default="not_processed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rawdataset",
            name="type",
            field=models.CharField(
                choices=[("tiff", "tiff"), ("excel", "excel"), ("csv", "csv")],
                max_length=100,
            ),
        ),
    ]
