# Generated by Django 5.0.1 on 2025-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_load_processing_chain_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZootechnicalDataCalabria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ID campione", models.CharField(max_length=100)),
                ("Data", models.DateField()),
                ("Periodo", models.CharField(max_length=100)),
                ("Cereali [loietto] (Peso secco [kg m-2])", models.FloatField()),
                (
                    "Leguminose [trifoglio bianco] (Peso secco [kg m-2])",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Altro [crucifere e brassicacee] (Peso secco [kg m-2])",
                    models.FloatField(blank=True, null=True),
                ),
                ("Peso totale (Peso secco [kg m-2])", models.FloatField()),
                ("SS 105°C", models.FloatField(blank=True, null=True)),
                ("SS REALE", models.FloatField(blank=True, null=True)),
                ("EE", models.FloatField(blank=True, null=True)),
                ("PG", models.FloatField(blank=True, null=True)),
                ("CENERI", models.FloatField(blank=True, null=True)),
                ("NDF", models.FloatField(blank=True, null=True)),
                ("ADF", models.FloatField(blank=True, null=True)),
                ("ADL", models.FloatField(blank=True, null=True)),
                ("Inizio pascolamento", models.DateField(blank=True, null=True)),
                (
                    "Utilizzazione",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "zootechnical_data_calabria",
            },
        ),
        migrations.AlterField(
            model_name="processeddataset",
            name="type",
            field=models.CharField(
                choices=[
                    ("db_table", "db_table"),
                    ("geoserver_layer", "geoserver_layer"),
                ],
                max_length=100,
            ),
        ),
    ]
