# Generated by Django 4.2.24 on 2025-11-05 14:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0034_auto_20200512_1431"),
        ("layers", "0044_alter_dataset_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiemnt1Sheet4",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cultivation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("biomass", models.CharField(blank=True, max_length=200, null=True)),
                ("n-no3 mg/kg soil", models.FloatField(blank=True, null=True)),
                ("n-nh4 mg/kg soil", models.FloatField(blank=True, null=True)),
                ("p olsen mg/kg soil", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("phase", models.IntegerField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "azoto_e_fosforo_soil",
                "verbose_name_plural": "azoto_e_fosforo_soil",
                "db_table": "azione_1_foglio_4",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiment1Sheet1",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("treatment", models.CharField(blank=True, max_length=200, null=True)),
                ("gy barley", models.FloatField(blank=True, null=True)),
                ("sy barley", models.FloatField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "1st_crops",
                "verbose_name_plural": "1st_crops",
                "db_table": "azione_1_foglio_1",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiment1Sheet2",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "cover crop systems",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("biomass cover crop (t/ha)", models.FloatField(blank=True, null=True)),
                ("n uptake (kg/ha)", models.FloatField(blank=True, null=True)),
                ("p uptake (kg/ha)", models.FloatField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "1st_crops_as_cover_crop",
                "verbose_name_plural": "1st_crops_as_cover_crop",
                "db_table": "azione_1_foglio_2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiment1Sheet3",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "cover crop species",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "type of cover termination",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tomato yield (kg/plant)", models.FloatField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "2nd_crops_pomodoro",
                "verbose_name_plural": "2nd_crops_pomodoro",
                "db_table": "azione_1_foglio_3",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiment3",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("tesi", models.CharField(max_length=50)),
                ("data", models.DateField(db_column="data")),
                ("ph", models.FloatField(blank=True, null=True)),
                ("ce", models.FloatField(blank=True, null=True)),
                ("corg", models.FloatField(blank=True, null=True)),
                ("ntot", models.FloatField(blank=True, null=True)),
                ("mbc", models.FloatField(blank=True, null=True)),
                ("mbn", models.FloatField(blank=True, null=True)),
                ("mbc/mbn", models.FloatField(blank=True, null=True)),
                ("rbas", models.FloatField(blank=True, null=True)),
                ("qmin", models.FloatField(blank=True, null=True)),
                ("qco2", models.FloatField(blank=True, null=True)),
                ("qco2/corg", models.FloatField(blank=True, null=True)),
                ("mbc/corg", models.FloatField(blank=True, null=True)),
                ("poxc", models.FloatField(blank=True, null=True)),
                ("pma acida", models.FloatField(blank=True, null=True)),
                ("pma alcalina", models.FloatField(blank=True, null=True)),
                ("fda", models.FloatField(blank=True, null=True)),
                ("ars", models.FloatField(blank=True, null=True)),
                ("b_glu", models.FloatField(blank=True, null=True)),
                ("urease", models.FloatField(blank=True, null=True)),
                ("bfi", models.FloatField(blank=True, null=True)),
                ("bfi*", models.FloatField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Dati Azione 3",
                "verbose_name_plural": "Dati Azione 3",
                "db_table": "dati_azione_3",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiment4",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("genotipo", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "trattamento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("replica", models.IntegerField(blank=True, null=True)),
                ("produzione kg/pianta", models.FloatField(blank=True, null=True)),
                ("biomassa g/pianta", models.FloatField(blank=True, null=True)),
                ("spad", models.FloatField(blank=True, null=True)),
                ("n balance index", models.FloatField(blank=True, null=True)),
                ("n content pianta", models.FloatField(blank=True, null=True)),
                ("nitrato riduttasi (nr)", models.FloatField(blank=True, null=True)),
                ("glutammina sintetasi (gs)", models.FloatField(blank=True, null=True)),
                ("glutammato (gogat)", models.FloatField(blank=True, null=True)),
                ("nrt2.1", models.FloatField(blank=True, null=True)),
                ("nrt2.3", models.FloatField(blank=True, null=True)),
                ("nrt2.4", models.FloatField(blank=True, null=True)),
                ("nrt3.1", models.FloatField(blank=True, null=True)),
                ("nr", models.FloatField(blank=True, null=True)),
                ("gs", models.FloatField(blank=True, null=True)),
                ("gogat", models.FloatField(blank=True, null=True)),
                ("clca", models.FloatField(blank=True, null=True)),
                ("lob37", models.FloatField(blank=True, null=True)),
                ("nrt1.7", models.FloatField(blank=True, null=True)),
                ("nrt2.7", models.FloatField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Dati Azione 4",
                "verbose_name_plural": "Dati Azione 4",
                "db_table": "azione_4",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiment5",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("campione", models.CharField(blank=True, max_length=200, null=True)),
                ("shannon", models.FloatField(blank=True, null=True)),
                ("simpson", models.FloatField(blank=True, null=True)),
                ("mntd", models.FloatField(blank=True, null=True)),
                ("fusarium", models.FloatField(blank=True, null=True)),
                ("rhizoctonia", models.FloatField(blank=True, null=True)),
                ("phytophtora", models.FloatField(blank=True, null=True)),
                ("data_campionamento", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("long", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Dati Azione 5",
                "verbose_name_plural": "Dati Azione 5",
                "db_table": "azione_5",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExperimentZootechnicalBasilicata",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("campione", models.CharField(blank=True, max_length=255, null=True)),
                ("pascolo", models.CharField(blank=True, max_length=255, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("prelievo", models.CharField(blank=True, max_length=255, null=True)),
                ("id nir", models.CharField(blank=True, max_length=255, null=True)),
                ("temperatura suolo °c", models.FloatField(blank=True, null=True)),
                ("umidità suolo %", models.FloatField(blank=True, null=True)),
                ("altezza pascolo cm", models.FloatField(blank=True, null=True)),
                ("temperatura aria °c", models.FloatField(blank=True, null=True)),
                ("piogge mm", models.FloatField(blank=True, null=True)),
                (
                    "biomassa verde totale (g/ 0,25 mq)",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "biomassa verde pulita dal secco e messo in stufa (g/ 0,25 mq)",
                    models.FloatField(blank=True, null=True),
                ),
                ("ndvi media", models.FloatField(blank=True, null=True)),
                ("ndvi mediana", models.FloatField(blank=True, null=True)),
                ("evi media", models.FloatField(blank=True, null=True)),
                ("evi mediana", models.FloatField(blank=True, null=True)),
                ("lai", models.FloatField(blank=True, null=True)),
                (
                    "biomassa secca totale (g/0,25 mq)",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "biomassa secca pulita dal secco (g/ 0,25 mq)",
                    models.FloatField(blank=True, null=True),
                ),
                ("% ss campione verde", models.FloatField(blank=True, null=True)),
                ("% ss campione pulito", models.FloatField(blank=True, null=True)),
                ("peso graminacee (g)", models.FloatField(blank=True, null=True)),
                ("peso leguminose (g)", models.FloatField(blank=True, null=True)),
                ("peso composite (g)", models.FloatField(blank=True, null=True)),
                ("peso altre (g)", models.FloatField(blank=True, null=True)),
                ("% graminacee", models.FloatField(blank=True, null=True)),
                ("% leguminose", models.FloatField(blank=True, null=True)),
                ("% composite", models.FloatField(blank=True, null=True)),
                ("% altre", models.FloatField(blank=True, null=True)),
                ("ss nir unibas", models.FloatField(blank=True, null=True)),
                ("ss ara", models.FloatField(blank=True, null=True)),
                ("ndf ara", models.FloatField(blank=True, null=True)),
                ("ndf nir unibas", models.FloatField(blank=True, null=True)),
                ("ndfunibas", models.FloatField(blank=True, null=True)),
                ("adf ara", models.FloatField(blank=True, null=True)),
                ("adl ss ara", models.FloatField(blank=True, null=True)),
                ("adf nir unibas", models.FloatField(blank=True, null=True)),
                ("adf unibas", models.FloatField(blank=True, null=True)),
                ("proteine nir unibas", models.FloatField(blank=True, null=True)),
                ("prot_insara", models.FloatField(blank=True, null=True)),
                ("protsolub ara", models.FloatField(blank=True, null=True)),
                ("protenine ara kjeldhal", models.FloatField(blank=True, null=True)),
                ("grassi ss ara", models.FloatField(blank=True, null=True)),
                (
                    "estratto etereo % nir unibas",
                    models.FloatField(blank=True, null=True),
                ),
                ("fibre ss ara", models.FloatField(blank=True, null=True)),
                ("ceneri ss ara", models.FloatField(blank=True, null=True)),
                ("ceneri % nir unibas", models.FloatField(blank=True, null=True)),
                ("amido ss ara", models.FloatField(blank=True, null=True)),
                ("mg tq ara", models.FloatField(blank=True, null=True)),
                ("s tq ara", models.FloatField(blank=True, null=True)),
                ("ca ara", models.FloatField(blank=True, null=True)),
                ("p tq ara", models.FloatField(blank=True, null=True)),
                ("k tq ara", models.FloatField(blank=True, null=True)),
                (
                    "famiglia nir",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Dati Azione zootecnica Basilicata",
                "verbose_name_plural": "Dati Azione zootecnica Basilicata",
                "db_table": "azione_zootecnica_basilicata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExperimentZootechnicalCalabria",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("id campione", models.IntegerField()),
                (
                    "cereali [loietto] (peso secco [kg m_2])",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "leguminose [trifoglio bianco] (peso secco [kg m_2])",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "altro [crucifere e brassicacee] (peso secco [kg m_2])",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "peso totale (peso secco [kg m_2])",
                    models.FloatField(blank=True, null=True),
                ),
                ("ss 105°c", models.FloatField(blank=True, null=True)),
                ("ss reale", models.FloatField(blank=True, null=True)),
                ("ee", models.FloatField(blank=True, null=True)),
                ("pg", models.FloatField(blank=True, null=True)),
                ("ceneri", models.FloatField(blank=True, null=True)),
                ("ndf", models.FloatField(blank=True, null=True)),
                ("adf", models.FloatField(blank=True, null=True)),
                ("adl", models.FloatField(blank=True, null=True)),
                ("periodo", models.FloatField(blank=True, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("inizio pascolamento", models.DateField(blank=True, null=True)),
                (
                    "utilizzazione",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Dati Azione zootecnica Calabria",
                "verbose_name_plural": "Dati Azione zootecnica Calabria",
                "db_table": "azione_zootecnica_calabria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetExperiment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "model_package",
                    models.CharField(
                        blank=True,
                        db_column="model_package",
                        help_text="Nome del modello Django nel formato 'app_label.ModelName' (es: 'farmtech.Experiment4')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "template_path",
                    models.CharField(
                        blank=True, db_column="template_path", max_length=255, null=True
                    ),
                ),
                (
                    "group_profile",
                    models.ForeignKey(
                        db_column="group_profile",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="groups.groupprofile",
                    ),
                ),
                (
                    "layer_dataset",
                    models.ForeignKey(
                        db_column="layer_dataset",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="layers.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset Experiment",
                "verbose_name_plural": "Dataset Experiments",
                "db_table": "dataset_experiments",
                "unique_together": {("layer_dataset", "group_profile")},
            },
        ),
        migrations.CreateModel(
            name="RoleChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_role",
                    models.CharField(
                        choices=[("manager", "Manager"), ("member", "Member")],
                        max_length=10,
                    ),
                ),
                ("motivazione", models.TextField()),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "group_profile",
                    models.ForeignKey(
                        db_column="group_profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.groupprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Change Request",
                "verbose_name_plural": "Role Change Requests",
                "db_table": "role_change_requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="RawFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=500)),
                (
                    "upload_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_column="upload_datetime"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("tiff", "TIFF"), ("excel", "Excel")], max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dataset_experiment",
                    models.ForeignKey(
                        db_column="dataset_experiment",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="farmtech.datasetexperiment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw File",
                "verbose_name_plural": "Raw Files",
                "db_table": "raw_files",
            },
        ),
    ]
